name: Fetch ASX Rate Tracker Data

on:
  schedule:
    # Run every hour during ASX trading hours (9 AM - 5 PM Sydney time)
    - cron: '0 23,0,1,2,3,4,5,6 * * *'  # UTC times for Sydney business hours
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main

jobs:
  fetch-asx-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 selenium webdriver-manager
        
    - name: Install Chrome for Selenium
      uses: browser-actions/setup-chrome@latest
      
    - name: Fetch ASX Data
      run: |
        python scripts/fetch_asx_live.py
        
    - name: Validate JSON
      run: |
        python -m json.tool data/market-odds.json > /dev/null
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/market-odds.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update ASX market odds data" && git push)
